title: "Here is Mahnaz with ideas and tutorials"
description: "Notes, tutorials, research updates, and random experiments."
theme: minima
author:
  name: "Mahnaz T-D"
  email: "m.talebi.dl@gmail.com"
minima:
  skin: auto
  social_links:
    - { platform: github,  user_url: "https://github.com/" }
    - { platform: x,       user_url: "https://x.com/" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/" }
# Show pages (about, tutorials) in the header
header_pages:
 header_pages:
  - about.md
  - ideas.md
  - my papers.md
  - tutorials.md
  - projects.md
  - research.md
  - contact.md
show_excerpts: true
paginate: 5
paginate_path: "/page:num"
plugins:
  - jekyll-paginate
google_analytics: ""
