title: "✦ Mahnaz TD | Linguistics & Ideas"
description: "Notes, tutorials, research updates and my papers."
remote_theme: "mmistakes/minimal-mistakes"

author:
  name: "Mahnaz T-D"
  email: "m.talebi.dl@gmail.com"

plugins:
  - jekyll-include-cache
  - jekyll-paginate

paginate: 6
paginate_path: "/page:num"
